### ISSUE TITLE
The structure of a jbuild init make no sense

### ISSUE THREAD

**Issue by Peaupote** [FauconFan/jbuild#2]
``` sh
$ ./jbuild  init src
```

produces the following arborescence:
``` sh
src:
srcs

src/srcs:
src.java
``` 

it makes no sense:
* nobody calls a directory src**s**
* jbuild init should ask nothing(default=src) or a package name
* why create a class ?
* why is the created class called src.java ????

**Comment by FauconFan** [comment]
The model has changed when you create a project. There is a folder src, and a Main.java into it, with main function. A few of others folders will added soon
