### ISSUE TITLE
MY FINGERs! #WorstProjectEver #Fingerism #NoHomo #FingersRulz #Illuminati 

### ISSUE THREAD

**Issue by firgaty** [FauconFan/jbuild#3]
WHY DOESN'T IT INSTALL DIRECTLY INTO MY PC WHEN I SNAP MY FINGERS?
LIKE SERIOUSLY ? I DON'T HAVE YOUR TIME!

**Comment by Peaupote** [comment]
I COMPLETELY AGREE WITH YOU. MY EYES BURNED WHEN I LOOKED AT YOUR SCRIPT

**Comment by FauconFan** [comment]
I don't have anythink to say. But love you my friends xd
