### ISSUE TITLE
WTF ? init && make "This is not a Jbuild folder..."

### ISSUE THREAD

**Issue by Peaupote** [FauconFan/jbuild#4]
By convention, init initialise the project for the current folder.
And we can't event build a project from an outside folder:
```sh
$ ./jbuild init Felix
$ ./jbuild make Felix
This is not a Jbuild folder...
```

Very disappointing... :triumph:

**Comment by FauconFan** [comment]
The model is not the same. If you want to make the project you have to be inside the project. As you did, you just create a folder project then you have to go into it. If you are already in your project folder not initialized. You have to do

$ jbuild init
$ jbuild make

;)
